[package]
name = "kip_hub"
version = "1.6.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["K.I.P. Studio"]
description = "High-performance modular Minecraft management suite and client engine."

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
rusqlite = { version = "0.40.2", features = ["bundled"] }
tokio = { version = "1.53.1", features = ["full"] }
reqwest = { version = "0.13.5", features = ["json"] }
dirs = "7.0.0"
keyring = "4.2.0"
machine-uid = "0.6.0"
base64 = "0.23.1"
lazy_static = "1.5.0"
parking_lot = "0.12.5"
log = "0.4.34"
simplelog = "0.12.2"
sysinfo = "0.39.6"
walkdir = "2.5.0"
sha1 = "0.11.0"
zip = "8.6.0"
image = "0.25.10"
chrono = "0.4.45"
regex = "1.13.1"
sha2 = "0.11.0"
fastnbt = "2.6.3"
flate2 = "1.1.10"
notify = "8.2.0"
discord-rich-presence = "1.1.0"
rdev = "0.5.3"
tokio-tungstenite = "0.30.0"
futures-util = "0.3.34"
url = "2.5.8"
uuid = { version = "1.26.1", features = ["v4"] }
urlencoding = "2.1.3"
tauri = { version = "2.12.0", features = [] }
tauri-plugin-updater = "2"
open = "5.4.4"

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }
